/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Logica.detalleVenta;
import Logica.fabricaElGuardian;
import Logica.iControladorVentas;
import Logica.producto;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gabri
 */
public class AltaVenta extends javax.swing.JInternalFrame {

    iControladorVentas ICV;
    /**
     * Creates new form AltaVenta
     */
    int altura = 100;
    int panel = 2;
    List<producto> listaproductos;
    List<detalleVenta> listaventa = new ArrayList<>();
    float PrecioTotal = 0;

    public AltaVenta() {
        initComponents();
        this.ICV = fabricaElGuardian.getInstance().getInstanceIControladorVentas();
        listaproductos = (List<producto>) ICV.obtenerProductos();
        DefaultTableModel modelo = (DefaultTableModel) TablaProductos.getModel();

        modelo.setRowCount(0);

        for (int i = 0; i < listaproductos.size(); i++) {

            producto pro = (producto) listaproductos.get(i);
            Object[] datos = {pro.getCodigo(), pro.getNombre(), pro.getPrecio(), pro.getCantidad()};

            modelo.addRow(datos);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tablaventa = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaProductos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        agregarproducto = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Preciototal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Alta Venta");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Productos");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Lista de venta");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(205, 698, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(228, 228, 228))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(438, 438, 438)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3))
        );

        Tablaventa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Precio", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tablaventa);

        TablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Precio", "Stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TablaProductos);

        jButton1.setText("Crear venta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        agregarproducto.setText("Agregar producto");
        agregarproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarproductoActionPerformed(evt);
            }
        });

        jButton3.setText("Salir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setText("Quitar Producto");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Total:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(419, 419, 419)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(agregarproducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(63, 63, 63)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Preciototal, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(agregarproducto)
                        .addComponent(jButton2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(Preciototal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addGap(53, 53, 53))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarproductoActionPerformed
       
        int a = TablaProductos.getSelectedRow();
        if (a == -1) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un producto");
            return;
        }
        producto produ = ICV.ObtenerProducto((Long) TablaProductos.getValueAt(TablaProductos.getSelectedRow(), 0));
        detalleVenta dv = new detalleVenta();      
        dv.setProducto(produ);
        
        DefaultTableModel modelo = (DefaultTableModel) Tablaventa.getModel();
        modelo.setRowCount(0);
       
        boolean existe=false;
        for (int x = 0; x < listaventa.size(); x++) {           
            detalleVenta detv = (detalleVenta) listaventa.get(x);
            producto pro = detv.getProducto();
            
            if(produ.getCodigo()==pro.getCodigo()){
                if(pro.getCantidad()>detv.getCantidad()){ 
                 detv.setCantidad(detv.getCantidad()+1);
                  }
                 existe=true;
            }
               
        
        }
        
        if(!existe)
        this.listaventa.add(dv);
        
        PrecioTotal= 0;
         for (int x = 0; x < listaventa.size(); x++) {           
            detalleVenta detv = (detalleVenta) listaventa.get(x);
            producto pro = detv.getProducto();
            
             PrecioTotal = PrecioTotal+detv.getCantidad()*detv.getProducto().getPrecio();
            Object[] datos = {pro.getCodigo(), pro.getNombre(), pro.getPrecio(), detv.getCantidad()};
            modelo.addRow(datos);
            
        }
        
        
        
        
           // PrecioTotal = PrecioTotal + (produ.getPrecio() * produ.getCantidad());
//////       for (int i = 0; i < listaventa.si
////       for (int i = 0; i < listaventa.size(); i++) {
////            
////            dv.setProducto(p);
////            producto pro = (producto) listaventa.get(i).getProducto();
////            if (pro.getCodigo() == p.getCodigo()) {
////                esta = true;
////            }
////        }
////        if (!esta) {
////            listaventa.add(dv);
////        }
////        DefaultTableModel modelo = (DefaultTableModel) Tablaventa.getModel();
////        modelo.setRowCount(0);
////        PrecioTotal = 0;
////        for (int x = 0; x < listaventa.size(); x++) {
////            producto produ = (producto) listaventa.get(x).getProducto();
////            PrecioTotal = PrecioTotal + (produ.getPrecio() * produ.getCantidad());
////            Object[] datos = {produ.getCodigo(), produ.getNombre(), produ.getPrecio(), produ.getCantidad()};
////            modelo.addRow(datos);
////        }
      this.Preciototal.setText("" + PrecioTotal);
    }//GEN-LAST:event_agregarproductoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        for (int x = listaventa.size() - 1; x >= 0; x--) {
            producto produ = (producto) listaventa.get(x).getProducto();
         //   produ.setCantidad(1);
            listaventa.remove(produ);
        }
         for (int x = listaproductos.size() - 1; x >= 0; x--) {
            producto produ = (producto) listaproductos.get(x);
         //   produ.setCantidad(1);
            listaventa.remove(produ);
        }
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (listaventa.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe agregar productos a la venta");
            return;
        }
        //aca va el altaventa 
        
       boolean funciono=true;
      
   //   ICV.AltaVenta(listaventa);
        if (funciono) {
            JOptionPane.showMessageDialog(null, "Venta realizada");
        } else {
            JOptionPane.showMessageDialog(null, "Error al realizar la venta");
        }
        DefaultTableModel modelo = (DefaultTableModel) Tablaventa.getModel();
        modelo.setRowCount(0);
        for (int x = listaventa.size() - 1; x >= 0; x--) {
            producto produ = (producto) listaventa.get(x).getProducto();
//            produ.setCantidad(1);
            listaventa.remove(produ);
        }
           for (int x = listaproductos.size() - 1; x >= 0; x--) {
            producto produ = (producto) listaproductos.get(x);
         //   produ.setCantidad(1);
            listaventa.remove(produ);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int a = Tablaventa.getSelectedRow();
        if (a == -1) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un producto");
            return;
        }
    
        
        boolean existe=false;
       
        Long cod= (Long) Tablaventa.getValueAt(Tablaventa.getSelectedRow(), 0);
        producto p = ICV.ObtenerProducto(cod);
        for (int i = 0; i < listaventa.size(); i++) {
            detalleVenta detv = (detalleVenta) listaventa.get(i);
            if (detv.getProducto().getCodigo() == p.getCodigo()) {
                if(detv.getCantidad()>1){
                    detv.setCantidad(detv.getCantidad()-1);
                     existe=true;
                    }
                
            }
        }
        if(!existe){
            for (int i = 0; i < listaventa.size(); i++) {
                detalleVenta detv = (detalleVenta) listaventa.get(i);
                if (detv.getProducto().getCodigo() == p.getCodigo()) 
                this.listaventa.remove(detv);
            
        }
        }
            
            
       
        DefaultTableModel modelo = (DefaultTableModel) Tablaventa.getModel();
        modelo.setRowCount(0);
        PrecioTotal = 0;
        for (int x = 0; x < listaventa.size(); x++) {
            detalleVenta detv = (detalleVenta) listaventa.get(x);
            producto pro = detv.getProducto(); 
            PrecioTotal = PrecioTotal+detv.getCantidad()*detv.getProducto().getPrecio();
            
            Object[] datos = {pro.getCodigo(), pro.getNombre(), pro.getPrecio(), detv.getCantidad()};
            modelo.addRow(datos);
        }
        this.Preciototal.setText("" + PrecioTotal);
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Preciototal;
    private javax.swing.JTable TablaProductos;
    private javax.swing.JTable Tablaventa;
    private javax.swing.JButton agregarproducto;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
