/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Logica.cliente;
import Logica.controladorCliente;
import Logica.fabricaElGuardian;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author jp
 */
public class JIF_clientesModificar extends javax.swing.JInternalFrame {

    private final String idCorreo;
    private fabricaElGuardian fabIns = fabricaElGuardian.getInstance();
    private controladorCliente contCliente = (controladorCliente) fabIns.getInstanceIControladorCliente();
    cliente cliente;
    private final JDesktopPane padre;

    /**
     * Creates new form JIF_clientesModificar
     *
     * @param cedula
     * @param jifClientes
     */
    public JIF_clientesModificar(String idCorreo, JDesktopPane jifClientes) {
        initComponents();
        this.idCorreo = idCorreo;
        cliente = new cliente();
        cargaCliente();
        this.padre = jifClientes;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jT_nombre = new javax.swing.JTextField();
        jT_apellido = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jT_cedula = new javax.swing.JTextField();
        jT_correo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jT_direccion = new javax.swing.JTextField();
        jT_telefono = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTA_comentario = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        btn_aceptar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        btn_resetPassw = new javax.swing.JButton();

        jLabel1.setText("Nombre");

        jT_apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_apellidoActionPerformed(evt);
            }
        });

        jLabel2.setText("Apellido");

        jLabel3.setText("Cedula");

        jLabel4.setText("Correo");

        jLabel5.setText("Direccion");

        jLabel6.setText("Telefono");

        jTA_comentario.setColumns(20);
        jTA_comentario.setRows(5);
        jScrollPane1.setViewportView(jTA_comentario);

        jLabel7.setText("Comentario:");

        btn_aceptar.setText("Aceptar");
        btn_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptarActionPerformed(evt);
            }
        });

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        btn_resetPassw.setText("Resetear Contraseña");
        btn_resetPassw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetPasswActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_resetPassw, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jT_telefono))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jT_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jT_correo, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jT_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(22, 22, 22)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jT_nombre)
                                    .addComponent(jT_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_aceptar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                                .addComponent(btn_cancelar)
                                .addGap(46, 46, 46))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jT_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jT_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jT_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jT_correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jT_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jT_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btn_resetPassw)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_aceptar)
                    .addComponent(btn_cancelar))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jT_apellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_apellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_apellidoActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        limpiar();
        recargarPadre();
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarActionPerformed
        modificarCliente();        // TODO add your handling code here:
    }//GEN-LAST:event_btn_aceptarActionPerformed

    private void btn_resetPasswActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetPasswActionPerformed
        resetPass();
    }//GEN-LAST:event_btn_resetPasswActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_aceptar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_resetPassw;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTA_comentario;
    private javax.swing.JTextField jT_apellido;
    private javax.swing.JTextField jT_cedula;
    private javax.swing.JTextField jT_correo;
    private javax.swing.JTextField jT_direccion;
    private javax.swing.JTextField jT_nombre;
    private javax.swing.JTextField jT_telefono;
    // End of variables declaration//GEN-END:variables
///////////////////funciones

    private void cargaCliente() {
        try {
            cliente = (cliente)contCliente.getCliente(idCorreo);
            jT_nombre.setText(cliente.getNombre());
            jT_apellido.setText(cliente.getApellido());
            jT_cedula.setText(cliente.getCedula());
            jT_cedula.setEditable(false);
            jT_cedula.setEnabled(false);
            jT_telefono.setText(cliente.getTel_cel());
            jT_direccion.setText(cliente.getDireccion());
            jT_correo.setText(cliente.getCorreo());
            jT_correo.setEditable(false);
            jT_correo.setEnabled(false);
        } catch (Exception e) {
            System.err.println(e.getMessage());

        }

    }

    private void modificarCliente() {
        int res = JOptionPane.showConfirmDialog(this, "Desea modificar los datos del cliente?");
        if (res == 0) {
            if (verificaDatos()) {
                cliente modificado = new cliente();
                modificado.setNombre(jT_nombre.getText());
                modificado.setApellido(jT_apellido.getText());
                modificado.setCedula(jT_cedula.getText());
                modificado.setCorreo(jT_correo.getText());
                modificado.setDireccion(jT_direccion.getText());
                modificado.setTel_cel(jT_telefono.getText());
                cliente.modificarme(modificado);
            }
            if (contCliente.modificarCliente(cliente)) {
                JOptionPane.showMessageDialog(this, "Cliente modificado con exito!");
                limpiar();
                recargarPadre();
                this.dispose();
            }
        }

    }

    private boolean verificaDatos() {
        if (jT_nombre.getText() == null) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un nombre!");
            jT_nombre.requestFocus();
            return false;
        }
        if (jT_apellido.getText() == null) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un apellido!");
            jT_apellido.requestFocus();;
            return false;
        }
        if (jT_cedula.getText() == null) {
            JOptionPane.showMessageDialog(this, "Debe ingresar una cedula!");
            jT_cedula.requestFocus();
            return false;
        }
        if (jT_correo.getText() == null) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un correo!");
            jT_correo.requestFocus();
            return false;
        }
        if (!contCliente.emailValido(jT_correo.getText())) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un correo valido!");
            jT_correo.requestFocus();
            return false;
        }
        if (jT_direccion.getText() == null) {
            JOptionPane.showMessageDialog(this, "Debe ingresar una direccion!");
            jT_direccion.requestFocus();
            return false;
        }
        if (jT_telefono.getText() == null) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un telefono!");
            jT_telefono.requestFocus();
            return false;

        }
        return true;
    }

    private void limpiar() {
        jTA_comentario.setText(null);
        jT_apellido.setText(null);
        jT_cedula.setText(null);
        jT_correo.setText(null);
        jT_direccion.setText(null);
        jT_nombre.setText(null);
        jT_telefono.setText(null);
    }

    private void resetPass() {
        int res = JOptionPane.showConfirmDialog(this, "Desea resetear la contraseña?");
        if (res == 0) {
            if (contCliente.resetearPassword(idCorreo)) {
                JOptionPane.showMessageDialog(this, "Contraseña reseteada con exito!");
            }
        }
    }

    private void recargarPadre() {
        JInternalFrame[] allFrames = this.padre.getAllFrames();
        for (JInternalFrame jif : allFrames) {
            if (jif instanceof JIF_clientes) {
                JIF_clientes jifCli = (JIF_clientes) jif;
                jifCli.cargarClientes(null);
            }
        }

    }
}
