/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Logica.ControladorReservas;
import Logica.cliente;
import Logica.controladorCliente;
import Logica.mascota;
import Logica.turno;
import Logica.utilidades;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Set;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jp
 */
public class JIF_reservarTurno extends javax.swing.JInternalFrame {

    private controladorCliente contC = controladorCliente.getInstance();
    private ControladorReservas contRes = ControladorReservas.getInstance();
    private utilidades util = utilidades.getInstance();
    private cliente cliente = null;
    private List<mascota> mascotasCli = null;
    private mascota mascotaCliente = null;
    List<turno> turnosDisponibles = new ArrayList<>();
    private List<String> serviciosLista = new ArrayList<>();

    public cliente getCliente() {
        return cliente;
    }

    public void setCliente(cliente cliente) {
        this.cliente = cliente;
    }

    /**
     * Creates new form JIF_reservarTurno
     */
    public JIF_reservarTurno() {
        initComponents();
        inicio();
        cargarClientes();
        cargarTurnosDisponibles();
        caragarServiciosList();
    }

    private void inicio() {
        DefaultComboBoxModel limpio = new DefaultComboBoxModel();
        jList_Clientes.setModel(limpio);
        jList_Servicios.setModel(limpio);
        jList_Tipo.setModel(limpio);
        jList_servicio.setModel(limpio);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList_Clientes = new javax.swing.JList<>();
        jlabClientes = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTabla_mascotas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jCombo_Turnos = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtxt_descripcion = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLab_idMascota = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList_servicio = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jList_Tipo = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btn_agregarServicio = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane6 = new javax.swing.JScrollPane();
        jList_Servicios = new javax.swing.JList<>();
        Servicios = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        btn_aceptar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        btn_nuevoTipo = new javax.swing.JButton();
        Jlab_foto = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();

        jList_Clientes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList_Clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList_ClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList_Clientes);

        jlabClientes.setText("Clientes");

        jTabla_mascotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTabla_mascotas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabla_mascotasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTabla_mascotas);

        jLabel1.setText("Mascota");

        jCombo_Turnos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Turno");

        jtxt_descripcion.setColumns(20);
        jtxt_descripcion.setRows(5);
        jScrollPane3.setViewportView(jtxt_descripcion);

        jLabel3.setText("Descripcion");

        jLab_idMascota.setText("id");

        jList_servicio.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(jList_servicio);

        jLabel5.setText("Servicio");

        jList_Tipo.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(jList_Tipo);

        jLabel6.setText("Tipo");

        jLabel7.setText("Duracion");

        btn_agregarServicio.setText("Agregar Servicio");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jList_Servicios.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane6.setViewportView(jList_Servicios);

        Servicios.setText("Servicios");

        jButton2.setText("Eliminar Servicio");

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btn_aceptar.setText("Aceptar");

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        btn_nuevoTipo.setText("Nuevo Tipo");

        Jlab_foto.setText("Foto");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLab_idMascota))
                    .addComponent(jlabClientes)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Jlab_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jCombo_Turnos, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6)
                            .addComponent(jScrollPane5)
                            .addComponent(btn_nuevoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_agregarServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(btn_aceptar)
                        .addGap(37, 37, 37)
                        .addComponent(btn_cancelar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Servicios)
                            .addComponent(jScrollPane6)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jlabClientes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Jlab_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLab_idMascota))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addComponent(jSeparator2)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Servicios)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_aceptar)
                    .addComponent(btn_cancelar))
                .addGap(50, 50, 50))
            .addComponent(jSeparator3)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jCombo_Turnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_nuevoTipo)))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_agregarServicio)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void jList_ClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList_ClientesMouseClicked
        cargarCliente(getIdCliente(jList_Clientes.getSelectedValue()));     // TODO add your handling code here:
    }//GEN-LAST:event_jList_ClientesMouseClicked

    private void jTabla_mascotasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabla_mascotasMouseClicked
        int row = jTabla_mascotas.rowAtPoint(evt.getPoint());
        this.seleccionarMascota((Long) jTabla_mascotas.getValueAt(row, 0));
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabla_mascotasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jlab_foto;
    private javax.swing.JLabel Servicios;
    private javax.swing.JButton btn_aceptar;
    private javax.swing.JButton btn_agregarServicio;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_nuevoTipo;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jCombo_Turnos;
    private javax.swing.JLabel jLab_idMascota;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jList_Clientes;
    private javax.swing.JList<String> jList_Servicios;
    private javax.swing.JList<String> jList_Tipo;
    private javax.swing.JList<String> jList_servicio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTabla_mascotas;
    private javax.swing.JLabel jlabClientes;
    private javax.swing.JTextArea jtxt_descripcion;
    // End of variables declaration//GEN-END:variables

/////////////////////////////////////////////////////funnciones///////////////////////////////////////////
    private void cargarClientes() {
        HashMap<String, String> clientesMascota = null;
        clientesMascota = (HashMap<String, String>) contC.getClientesMascota();
        DefaultListModel<String> modeloLista = new DefaultListModel<>();
        Iterator it = (Iterator) clientesMascota.keySet().iterator();
        while (it.hasNext()) {
            String key = (String) it.next();
            String cadena = null;
            cadena = key + "-" + (String) clientesMascota.get(key);
            modeloLista.addElement(cadena);
        }
        jList_Clientes.setModel(modeloLista);
    }

    private void cargarCliente(String idCorreo) {
        setCliente((cliente) contC.getCliente(idCorreo));
        jTabla_mascotas.setModel(new DefaultTableModel(0, 0));//limpio el modelo de la tabla antes de cargar el nuevo
        cargarMascotasCliente(getCliente().getMascotasCliente());
        this.mascotasCli = (List<mascota>) getCliente().getMascotasCliente();

    }

    private String getIdCliente(String selectedValue) {
        String[] split = selectedValue.split("-");
        return split[0];
        // return Long.valueOf(split[0]);
    }

    private void cargarMascotasCliente(List<mascota> mascotasCliente) {
        DefaultTableModel dtm = null;
        String[] filtro = {"Cliente"};
        List<String> palabras;
        palabras = util.filtrarPalabras((String[]) util.cabeceras(mascotasCliente.get(0)), filtro);
        dtm = new DefaultTableModel(palabras.toArray(), 0);
        for (mascota msc : mascotasCliente) {
            Object[] data = {msc.getId(), msc.getNombre(), msc.getRaza().getRaza(), msc.getDescripcion()};
            dtm.addRow(data);
        }
        jTabla_mascotas.setModel(dtm);
        util.resizeColumnWidth(jTabla_mascotas);
    }

    private void seleccionarMascota(Long id) {
        this.mascotaCliente = (mascota) this.getMascota(id);
        cargarFoto(this.mascotaCliente);
        jLab_idMascota.setText(id.toString());

    }

    private mascota getMascota(Long id) {

        for (mascota msc : this.mascotasCli) {
            if (msc.getId().compareTo(id) == 0) {
                return msc;
            }

        }

        return null;
    }

    private void cargarFoto(mascota mascota) {

        BufferedImage image = (BufferedImage) util.dameEstaImagen(mascota.getFoto());
        Jlab_foto.setIcon(new ImageIcon(mascota.getFoto()));
        Image scaledInstance = image.getScaledInstance(200, 180, Image.SCALE_DEFAULT);
        Jlab_foto.setIcon(new ImageIcon(scaledInstance));
        Jlab_foto.setText(null);
    }

    private void cargarTurnosDisponibles() {
        this.turnosDisponibles = (ArrayList<turno>) contRes.getTurnos();
        int numTurno = 1;
        JComboBox<String> comboTurnos = new JComboBox<>();
        comboTurnos.addItem("Seleccionar Turno");
        for (turno turnoDisponible : turnosDisponibles) {
            comboTurnos.addItem("Turno: " + numTurno + " -- " + turnoDisponible.getHora() + " Hs");
            numTurno++;
        }
        jCombo_Turnos.setModel(comboTurnos.getModel());
    }

    private turno getTurno(String hora) {
        turno tr = null;
        for (turno turD : this.turnosDisponibles) {
            if (turD.getHora().equals(hora)) {
                tr = turD;
            }

        }
        return tr;
    }

    private String obtenerHora(String valorCombo) {
        String[] corte1 = valorCombo.split(" -- ");
        String[] corteFInal = corte1[1].split(" ");
        return corteFInal[0];

    }

    private void cargarServiciosDisponibles() {

    }

    private void caragarServiciosList() {
        DefaultListModel modeloListaSer =(DefaultListModel) new DefaultListModel();
        modeloListaSer.addElement("Baño");
        modeloListaSer.addElement("Esquila");
        modeloListaSer.addElement("Paseo");
        jList_Servicios.setModel(modeloListaSer);
    }
}
